name: Prepare Darwin-VM Files

on:
  workflow_dispatch:
    inputs:
      ipsw_url:
        description: 'Direct URL to the 17.0.1 IPSW'
        required: true
        default: 'https://updates.cdn-apple.com/2023FallFCS/fullrestores/042-55433/87BA2B5F-F32A-4C61-8E58-82FAC1103C5A/iPhone13,2,iPhone13,3_17.0.1_21A340_Restore.ipsw' 
      device_name:
        description: 'Device Identifier (e.g. iPhone13,2)'
        required: true
        default: 'iPhone13,2'

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Install ipsw
        run: |
          brew install ipsw
        
      - name: Set up Environment & Run get_files
        env:
          DEVNAME: ${{ github.event.inputs.device_name }}
          URL: ${{ github.event.inputs.ipsw_url }}
        run: |
          chmod +x get_files.sh fix_perms.sh
          ./get_files.sh

      - name: Fix Permissions on macOS
        run: |
          ./fix_perms.sh firmware/ramdisk.dmg

      - name: Archive Firmware Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vm-firmware
          path: firmware/
